### PR TITLE
fixed display of critical risks in report tab, created sample sra 

### LINKED ISSUE #288: [Issue]: Critical risks are not displayed in the ISRA Report panel
### Issue Description

When a risk level is set to Critical
image
It is not displayed in the report:
image

### Duplicate Steps

Create a risk
Link it to a business asset with only critical values
Make the 'Risk evaluation' Very High
Go to ISRA Report panel

### Expected Results

Be able to see the critical risks in ISRA Report panel

### Version Detected

1.1.0 (Default)

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by DylanAwThales**
### Changes
*   **Sorting and counts**
    *   Add a critical bucket to the risk sorter and count decisions into `criticalRisk` so totals match the table and chart.
        *   `app/src/tabs/Report/renderer.js:286`: define critical array.
        *   `app/src/tabs/Report/renderer.js:306`: add `criticalRisk` array.
        *   `app/src/tabs/Report/renderer.js:313`: populate `sortedRisk.critical` and increment `criticalRisk`.
*   **Table rendering**
    *   Update `renderRisk` to handle Critical, color it red.
        *   `app/src/tabs/Report/renderer.js:248`: add Critical color and bold logic.
*   **Chart**
    *   Extend chart to include a Critical dataset and update it reliably:
        *   `app/src/tabs/Report/renderer.js:28`: change `generateGraph` signature to accept `criticalRisk`.
        *   Add a new dataset labeled "Critical" (red), order datasets as Low,Medium,High,Critical for readability.
*   **Render order**
    *   Ensure Critical risks render above High/Medium/Low:
        *   `app/src/tabs/Report/renderer.js:348`: call `renderRisk(sortedRisk, 'critical')` before others.
*   **Refactored Code**
    *   Ensured code followed best practices

### Verification
* Manual steps:
    1. Load project in doc/resources/sample001.sra.
    2. Open the Report tab.
    3. Confirm:
        * The risk appears in the table with dark-red text and a bolded level.
        * The bar chart shows a “Critical” legend entry and the counts match the table’s decision splits (Accept/Transfer/Mitigate).
        * Change decisions on a Critical risk and verify the chart updates to the correct column in the stack.
        
Fixes #288

### CODE REVIEW

File: app/src/tabs/Report/renderer.js [hunk 1]
```diff
@@ -1,14 +1,14 @@
 /*----------------------------------------------------------------------------
 *
-*     Copyright © 2022 THALES. All Rights Reserved.
- *
+*     Copyright © 2025 THALES. All Rights Reserved.
```
Comment (Alvin-JohnPagente) [inline app/src/tabs/Report/renderer.js]: Should be 2022-2025

File: app/src/tabs/Report/renderer.js
Comment (Alvin-JohnPagente) [inline app/src/tabs/Report/renderer.js]: The color values are used in multiple places. Can we define a constant?
